//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyTaxCollectionCMS.Dal.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class AD_CLIENT_DETAIL_MST
    {
        public int CLIENT_ID { get; set; }
        public string C_NAME { get; set; }
        public string CLIENT_TITLE { get; set; }
        public string C_FIRST_NAME { get; set; }
        public string C_MIDDLE_NAME { get; set; }
        public string C_LAST_NAME { get; set; }
        public Nullable<System.DateTime> C_DOB { get; set; }
        public Nullable<int> LOCATION_ID { get; set; }
        public Nullable<int> TALUKA_ID { get; set; }
        public Nullable<int> AD_DISTRICT_ID { get; set; }
        public Nullable<int> CITY_ID { get; set; }
        public Nullable<int> STATE_ID { get; set; }
        public Nullable<int> COUNTRY_ID { get; set; }
        public string COMPANY_NAME { get; set; }
        public string COM_ADD1 { get; set; }
        public string COM_ADD2 { get; set; }
        public int SMS_PROVIDER_ID { get; set; }
        public System.DateTime REG_DATE { get; set; }
        public System.DateTime EXP_DATE { get; set; }
        public string MOBILE_NO { get; set; }
        public string EMAIL { get; set; }
        public string CITY { get; set; }
    }
}
