//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyTaxCollectionCMS.Dal.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class AD_MODULE_MST
    {
        public int ADMM_MODULE_ID { get; set; }
        public string ADMM_MODULE_CODE { get; set; }
        public string ADMM_MODULE_NAME { get; set; }
        public bool ADMM_STATUS { get; set; }
        public string ADMM_MOD_SOURCE { get; set; }
        public int SEQ_NO { get; set; }
        public System.DateTime LAST_UPDATE { get; set; }
        public string DISPLAY_NAME { get; set; }
        public string IMG_NORMAL { get; set; }
        public string IMG_ACTIVE { get; set; }
    }
}
