//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyTaxCollectionCMS.Dal.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class AD_MODULE_OBJECT
    {
        public int ADMO_OBJECT_ID { get; set; }
        public string ADMO_OBJECT_NAME { get; set; }
        public int ADMM_MODULE_ID { get; set; }
        public string ADMO_OBJECT_TYPE { get; set; }
        public bool ADMO_STATUS { get; set; }
        public string ADMO_SOURCE { get; set; }
        public int ADMO_DIS_SRNO { get; set; }
        public System.DateTime LAST_UPDATE { get; set; }
        public string ADMO_DISPLAY_NAME { get; set; }
        public string IMG_NORMAL { get; set; }
        public string IMG_ACTIVE { get; set; }
        public string bireport_file { get; set; }
        public string TOOLTIP_DESCIP { get; set; }
    }
}
