//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyTaxCollectionCMS.Dal.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class AD_MODULE_OBJECT_CONTROL
    {
        public int ADMOC_CONTROL_ID { get; set; }
        public int ADMM_MODULE_ID { get; set; }
        public int ADMO_OBJECT_ID { get; set; }
        public string CONTROL_NAME { get; set; }
        public string CONTROL_TYPE { get; set; }
        public string CONTROL_SOURCE { get; set; }
        public bool CONTROL_STATUS { get; set; }
        public string DISPLAY_NAME { get; set; }
        public System.DateTime LAST_UPDATE { get; set; }
        public string IMG_NORMAL { get; set; }
        public string IMG_ACTIVE { get; set; }
    }
}
