//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyTaxCollectionCMS.Dal.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class AD_STATE_MST
    {
        public int STATE_ID { get; set; }
        public string STATE_NAME { get; set; }
        public Nullable<int> COUNTRY_ID { get; set; }
    }
}
