//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyTaxCollectionCMS.Dal.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class AD_TALUKA_MST
    {
        public int TALUKA_ID { get; set; }
        public string TALUKA_NAME { get; set; }
        public int DISTRICT_ID { get; set; }
    }
}
