//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyTaxCollectionCMS.Dal.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class AD_USER_LOG_MST
    {
        public long TRNO { get; set; }
        public Nullable<byte> SERVER_ID { get; set; }
        public Nullable<int> APP_ID { get; set; }
        public Nullable<int> ADUM_USER_CODE { get; set; }
        public string ADUM_USER_ID { get; set; }
        public Nullable<System.DateTime> LOGIN_TIME { get; set; }
        public Nullable<System.DateTime> LOGOUT_TIME { get; set; }
        public Nullable<bool> LOGIN_STATUS { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE { get; set; }
        public string IP_ADDRESS { get; set; }
    }
}
