//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyTaxCollectionCMS.Dal.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class AD_USER_ROLE_MST
    {
        public int ADURM_ID { get; set; }
        public int APP_ID { get; set; }
        public int ADUM_USER_CODE { get; set; }
        public int ADMOC_CONTROL_ID { get; set; }
        public bool ADURM_VIEW { get; set; }
        public System.DateTime LAST_UPDATE { get; set; }
        public int ADMO_OBJECT_ID { get; set; }
        public int ADMM_MODULE_ID { get; set; }
    }
}
