//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyTaxCollectionCMS.Dal.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEVICE_DETAILS
    {
        public int DEVICE_DETAIL_Id { get; set; }
        public string DEVICE_ID { get; set; }
        public string FCM_ID { get; set; }
        public string DEVICE_TYPE { get; set; }
        public Nullable<int> APP_ID { get; set; }
        public Nullable<int> ADUM_USER_CODE { get; set; }
        public Nullable<System.DateTime> INSTALL_DATE { get; set; }
    }
}
