//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyTaxCollectionCMS.Dal.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE_ATTENDANCE
    {
        public int DA_ID { get; set; }
        public Nullable<int> APP_ID { get; set; }
        public Nullable<int> ADUM_USER_CODE { get; set; }
        public string START_LAT { get; set; }
        public string START_LONG { get; set; }
        public string END_LAT { get; set; }
        public string END_LONG { get; set; }
        public Nullable<System.DateTime> DA_START_DATETIME { get; set; }
        public Nullable<System.DateTime> DA_END_DATETIME { get; set; }
        public string VT_ID { get; set; }
        public string DA_START_NOTE { get; set; }
        public string DA_END_NOTE { get; set; }
        public string VEHICLE_NUMBER { get; set; }
        public string BATTERY_STATUS { get; set; }
        public Nullable<int> TOTAL_KM { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
    }
}
