//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyTaxCollectionCMS.Dal.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class GOOGLE_API_HIT
    {
        public int ID { get; set; }
        public string API_KEY { get; set; }
        public string EMAIL_ID { get; set; }
        public Nullable<System.DateTime> HIT_DATE { get; set; }
        public Nullable<int> HIT_COUNT { get; set; }
    }
}
