//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyTaxCollectionCMS.Dal.DataContexts
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PropertyTaxCollectionCMSMain_Entities : DbContext
    {
        public PropertyTaxCollectionCMSMain_Entities()
            : base("name=PropertyTaxCollectionCMSMain_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AD_CITY_MST> AD_CITY_MST { get; set; }
        public virtual DbSet<AD_CLIENT_DETAIL_MST> AD_CLIENT_DETAIL_MST { get; set; }
        public virtual DbSet<AD_CLIENT_MODULE> AD_CLIENT_MODULE { get; set; }
        public virtual DbSet<AD_MODULE_MST> AD_MODULE_MST { get; set; }
        public virtual DbSet<AD_MODULE_OBJECT> AD_MODULE_OBJECT { get; set; }
        public virtual DbSet<AD_MODULE_OBJECT_CONTROL> AD_MODULE_OBJECT_CONTROL { get; set; }
        public virtual DbSet<AD_STATE_MST> AD_STATE_MST { get; set; }
        public virtual DbSet<AD_TALUKA_MST> AD_TALUKA_MST { get; set; }
        public virtual DbSet<AD_USER_LOG_MST> AD_USER_LOG_MST { get; set; }
        public virtual DbSet<AD_USER_MODULE> AD_USER_MODULE { get; set; }
        public virtual DbSet<AD_USER_MST> AD_USER_MST { get; set; }
        public virtual DbSet<AD_USER_ROLE_MST> AD_USER_ROLE_MST { get; set; }
        public virtual DbSet<ADMIN_CONTACT> ADMIN_CONTACT { get; set; }
        public virtual DbSet<APP_CONNECTION> APP_CONNECTION { get; set; }
        public virtual DbSet<APP_DETAILS> APP_DETAILS { get; set; }
        public virtual DbSet<DEVICE_DETAILS> DEVICE_DETAILS { get; set; }
        public virtual DbSet<EMPLOYEE_ATTENDANCE> EMPLOYEE_ATTENDANCE { get; set; }
        public virtual DbSet<GOOGLE_API_HIT> GOOGLE_API_HIT { get; set; }
        //public virtual DbSet<LOCATION> LOCATIONs { get; set; }
        public virtual DbSet<TAX_CATEGORY_TYPE> TAX_CATEGORY_TYPE { get; set; }
        public virtual DbSet<TAX_COLLECTION_DETAIL> TAX_COLLECTION_DETAIL { get; set; }
        public virtual DbSet<TAX_PAYMENT_TYPE> TAX_PAYMENT_TYPE { get; set; }
    }
}
